services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "7776:7776"
    volumes:
      - ../backend:/app

  frontend:
    image: nginx:alpine
    volumes:
      - ../frontend:/usr/share/nginx/html:ro
    ports:
      - "7777:80"
